on:
  push:
    branches:
       - master
  workflow_dispatch:

jobs:
  balena_cloud_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: balena-io/deploy-to-balena-action@master
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: gh_scott_hamilton/balena-ntfy
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
